In [79]:
import pandas as pd

In [80]:
retail = pd.read_csv('D:\\Программы\\Karpov.Courses - Аналитик данных (2022)\Часть 1\\Задания\\5_data.csv.zip', compression='zip', encoding='ISO-8859-1')
retail_columns = retail.columns

In [81]:
retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [82]:
retail.shape

(541909, 8)

In [83]:
retail.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [84]:
retail_new = retail.drop_duplicates()

In [85]:
retail_new.shape

(536641, 8)

In [86]:
retail_new['InvoiceNo'].str.startswith('C').sum()

np.int64(9251)

In [87]:
retail_new.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [88]:
#InvoiceNo — номер транзакции
#StockCode — код товара
# Description — описание товара
#Quantity — количество единиц товара, добавленных в заказ
#InvoiceDate — дата транзакции
#UnitPrice — цена за единицу товара
#CustomerID — id клиента
#Country — страна, где проживает клиент

In [89]:
retail_new['InvoiceNo'].str.startswith('N').sum()

np.int64(0)

In [93]:
retail = retail_new.drop_duplicates(subset='InvoiceNo')
germany_top = retail.query('Country == "Germany"')\
    .groupby('CustomerID', as_index=False)\
    .agg({'InvoiceNo': 'count'})

In [128]:
quily = germany_top.InvoiceNo.quantile(0.8)
germany_top1 = germany_top.query(f'InvoiceNo  > {quily}').CustomerID
retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,12/1/2010 8:35,5.95,13047.0,United Kingdom
...,...,...,...,...,...,...,...,...
541865,581583,20725,LUNCH BAG RED RETROSPOT,40,12/9/2011 12:23,1.45,13777.0,United Kingdom
541867,581584,20832,RED FLOCK LOVE HEART PHOTO FRAME,72,12/9/2011 12:25,0.72,13777.0,United Kingdom
541869,581585,22481,BLACK TEA TOWEL CLASSIC DESIGN,12,12/9/2011 12:31,0.39,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,12/9/2011 12:49,2.95,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France

In [125]:
top_retail_germany = retail[retail['CustomerID'].isin(germany_top1)]

In [126]:
top_retail_germany
#InvoiceNo — номер транзакции
#StockCode — код товара
# Description — описание товара
#Quantity — количество единиц товара, добавленных в заказ
#InvoiceDate — дата транзакции
#UnitPrice — цена за единицу товара
#CustomerID — id клиента
#Country — страна, где проживает клиент

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1109,536527,22809,SET OF 6 T-LIGHTS SANTA,6,12/1/2010 13:04,2.95,12662.0,Germany
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,12/1/2010 14:33,1.95,12472.0,Germany
3338,C536622,22752,SET 7 BABUSHKA NESTING BOXES,-2,12/2/2010 10:37,8.50,12471.0,Germany
6602,536967,POST,POSTAGE,1,12/3/2010 12:57,18.00,12600.0,Germany
6965,536983,22331,WOODLAND PARTY BAG + STICKER SET,8,12/3/2010 14:30,1.65,12712.0,Germany
...,...,...,...,...,...,...,...,...
535050,581183,22199,FRYING PAN RED RETROSPOT,6,12/7/2011 16:24,1.25,12569.0,Germany
535060,581184,22221,CAKE STAND LOVEBIRD 2 TIER PINK,6,12/7/2011 16:24,2.95,12569.0,Germany
537403,581266,23561,SET OF 6 RIBBONS PARTY,12,12/8/2011 11:25,2.89,12621.0,Germany
538555,C581409,84946,ANTIQUE SILVER T-LIGHT GLASS,-1,12/8/2011 14:08,1.25,12476.0,Germany
541718,581570,22141,CHRISTMAS CRAFT TREE TOP ANGEL,6,12/9/2011 11:59,2.10,12662.0,Germany

In [156]:
top_retail_germany_filtered = top_retail_germany.query('Description != "POST"')
top_retail_germany_filtered.groupby('StockCode', as_index=False)\
    .agg({'InvoiceNo': 'count'})\
    .sort_values('InvoiceNo', ascending=False)\
    .sum(int'InvoiceNo')

SyntaxError: invalid syntax (4216951313.py, line 5)