In [6]:
import pandas as pd

In [7]:
bookings = pd.read_csv(r'D:\Программы\Karpov.Courses - Аналитик данных (2022)\Часть 1\Задания\Данные для Минипроектов\2_bookings.csv' , sep = ';')

In [8]:
rows, cols = bookings.shape
print(f'{rows = }, {cols = }')

rows = 119390, cols = 21

In [9]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Hotel                      119390 non-null  object
 1   Is Canceled                119390 non-null  int64
 2   Lead Time                  119390 non-null  int64
 3   arrival full date          119390 non-null  object
 4   Arrival Date Year          119390 non-null  int64
 5   Arrival Date Month         119390 non-null  object
 6   Arrival Date Week Number   119390 non-null  int64
 7   Arrival Date Day of Month  119390 non-null  int64
 8   Stays in Weekend nights    119390 non-null  int64
 9   Stays in week nights       119390 non-null  int64
 10  stays total nights         119390 non-null  int64
 11  Adults                     119390 non-null  int64
 12  Children                   119386 non-null  float64
 13  Babies                     119390 non-null  int64
 14  Meal                       119390 non-null  object
 15  Country                    118902 non-null  object
 16  Reserved Room Type         119390 non-null  object
 17  Assigned room type         119390 non-null  object
 18  customer type              119390 non-null  object
 19  Reservation Status         119390 non-null  object
 20  Reservation status_date    119390 non-null  object
dtypes: float64(1), int64(10), object(10)
memory usage: 19.1+ MB

In [10]:
bookings.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [11]:
bookings.columns = bookings.columns.str.replace(' ', '_').str.lower()

In [12]:
bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [13]:
bookings.head(10)

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,FB,PRT,C,C,Transient,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015-07-01,2015,July,27,1,0,3,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-05-06
9,Resort Hotel,1,75,2015-07-01,2015,July,27,1,0,3,...,2,0.0,0,HB,PRT,D,D,Transient,Canceled,2015-04-22

In [14]:
bookings.loc[bookings.is_canceled ==0].country.value_counts().head

<bound method NDFrame.head of country
PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
       ...
KIR        1
ATF        1
TJK        1
SLE        1
FRO        1
Name: count, Length: 165, dtype: int64>

In [15]:
bookings.groupby('hotel').stays_total_nights.mean().round(2)

hotel
City Hotel      2.98
Resort Hotel    4.32
Name: stays_total_nights, dtype: float64

In [16]:
sm = bookings.query('reserved_room_type != assigned_room_type')
sd = sm.shape
print(sd)

(14917, 21)

In [21]:
bookings.groupby('arrival_date_year')['arrival_date_month'].agg(lambda x: x.value_counts().index[0])

arrival_date_year
2015    September
2016      October
2017          May
Name: arrival_date_month, dtype: object

In [29]:
bookings.groupby(['arrival_date_month', 'arrival_date_year']).is_canceled.sum().nlargest(1)

arrival_date_month  arrival_date_year
May                 2017                 2762
Name: is_canceled, dtype: int64

In [22]:
bookings

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07